# File: .github/workflows/repo-sync.yml    建立一个分支，把此文件放进分支的AC里
name: 同步
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: 同步
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: V2P
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/elecV2/elecV2P.git"
          source_branch: "master"
          destination_branch: "V2P"
          github_token: ${{ secrets.PAT }}
          
      - name: jd-base
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/dockere/jd-base.git"
          source_branch: "master"
          destination_branch: "dockere"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
          
      - name: hundun
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/whyour/hundun.git"
          source_branch: "master"
          destination_branch: "whyour"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}          

      - name: 肥皂
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/age174/-.git"
          source_branch: "main"
          destination_branch: "feizao"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}

      - name: Sunert
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Sunert/Scripts.git"
          source_branch: "master"
          destination_branch: "Sunert"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
          
      - name: CenBoMin
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/CenBoMin/GithubSync.git"
          source_branch: "main"
          destination_branch: "CenBoMin"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }} 


      - name: ziye
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ziye888/JavaScript.git"
          source_branch: "main"
          destination_branch: "ziye"
          github_token: ${{ secrets.PAT }}
